#!/usr/bin/env bash
# Gracefully reloads Gunicorn without downtime

# Find the master process ID of Gunicorn and send the HUP signal to it
ps aux | grep gunicorn | grep master | awk '{print $2}' | xargs kill -HUP
