#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

# Find the master Gunicorn process PID using pgrep
PIDS=$(pgrep -f "gunicorn" | grep -v grep | grep -v "reload_gunicorn")

# Check if PIDs are found
if [ -z "$PIDS" ]; then
  echo "Gunicorn master process not found."
  exit 1
fi

# Send the SIGHUP signal to the master process to reload gracefully
for PID in $PIDS; do
  kill -HUP $PID
done

echo "Gunicorn gracefully reloaded."
